import type { ShjTheme } from "../types.ts";

// GitHub Dark Default, as generated by primer/github-vscode-theme
const theme: ShjTheme = {
  name: "github-dark",
  scheme: "dark",
  bg: "#0d1117",
  fg: "#e6edf3",
  numbers: "#8b949e",
  tokens: {
    // `keyword`, which the theme also gives every operator
    kwd: "#ff7b72",
    oper: "#ff7b72",
    // `message.error` and `invalid.*`, a paler red than the keywords
    err: "#ffa198",
    deleted: "#ffa198",
    class: "#ffa657",
    cmnt: "#8b949e",
    // `brackethighlighter.*`, which the dark themes share with the comments
    bracket: "#8b949e",
    num: "#79c0ff",
    bool: "#79c0ff",
    type: "#79c0ff",
    section: "#79c0ff",
    var: "#79c0ff",
    str: "#a5d6ff",
    func: "#d2a8ff",
    insert: "#7ee787",
  },
};

export default theme;
