import type { ShjTheme } from "../types.ts";

// GitHub Dark Dimmed, as generated by primer/github-vscode-theme — a palette of
// its own rather than {@link githubDark} on a lighter background
const theme: ShjTheme = {
  name: "github-dim",
  scheme: "dark",
  bg: "#22272e",
  fg: "#adbac7",
  numbers: "#768390",
  tokens: {
    // `keyword`, which the theme also gives every operator
    kwd: "#f47067",
    oper: "#f47067",
    // `message.error` and `invalid.*`, a paler red than the keywords
    err: "#ff938a",
    deleted: "#ff938a",
    class: "#f69d50",
    cmnt: "#768390",
    // `brackethighlighter.*`, which the dark themes share with the comments
    bracket: "#768390",
    num: "#6cb6ff",
    bool: "#6cb6ff",
    type: "#6cb6ff",
    section: "#6cb6ff",
    var: "#6cb6ff",
    str: "#96d0ff",
    func: "#dcbdfb",
    insert: "#8ddb8c",
  },
};

export default theme;
