import type { ShjTheme } from "../types.ts";

// GitHub Light Default, as generated by primer/github-vscode-theme
const theme: ShjTheme = {
  name: "github-light",
  scheme: "light",
  bg: "#fff",
  fg: "#1f2328",
  numbers: "#6e7781",
  tokens: {
    // `keyword`, which the theme also gives every operator
    kwd: "#cf222e",
    oper: "#cf222e",
    // `message.error` and `invalid.*`, a darker red than the keywords
    err: "#82071e",
    deleted: "#82071e",
    class: "#953800",
    cmnt: "#6e7781",
    // `brackethighlighter.*`, the one bracket color the theme carries
    bracket: "#57606a",
    num: "#0550ae",
    bool: "#0550ae",
    type: "#0550ae",
    section: "#0550ae",
    var: "#0550ae",
    str: "#0a3069",
    func: "#8250df",
    insert: "#116329",
  },
};

export default theme;
