/**
 * Render every bundled theme as a single SVG, for the Themes section of the
 * README.
 *
 * One card per theme: a code sample highlighted with that theme — the palette
 * where a reader actually meets it — over a strip of raw swatches, one per
 * token type, so the colors a short sample never reaches (`err`, `deleted`,
 * `insert`, …) are still on the page. A token a theme leaves undefined gets a
 * dashed outline rather than a color: that token inherits `fg`.
 *
 * `scripts/theme-hero.ts` is the sister figure — the same themes as a stacked
 * deck, for the top of the README. Both draw with `scripts/_svg.ts`.
 *
 * Usage: `pnpm theme-palette` (`--out <path>`, `--columns <n>`)
 */

import { parseArgs } from "node:util";

import { TOKENS } from "../src/tokens.ts";
import type { ShjTheme } from "../src/types.ts";
import {
  attr,
  CHAR,
  drawCode,
  drawSwatches,
  type Entry,
  escape,
  FONT,
  LINE,
  MUTED,
  sampleColumns,
  sampleLines,
  SIZE,
  swatchSlots,
  swatchWidth,
  themes,
  writeSvg,
} from "./_svg.ts";

/**
 * The sample every card highlights.
 *
 * Chosen for coverage rather than for meaning: between them these lines carry
 * `cmnt`, `kwd`, `str`, `esc`, `func`, `type`, `bool`, `num`, `oper`, `bracket`
 * and plain text, which is most of what a theme colors. The rest is on the
 * swatch strip.
 */
const SAMPLE = `// tiny, synchronous, zero-dependency
import { codeToHtml } from "rangi";

export function render(code: string, wrap = true) {
  const n = code.split("\\n").length ?? 0;
  return codeToHtml(code, { lang: "ts", n, wrap });
}`;

const LANG = "ts";

// Card geometry.
const PAD = 16;
const TITLE = 20;
const SWATCH = 13;
const SWATCH_GAP = 4;
const GAP = 20;

const first = themes[0]?.theme as ShjTheme;
const rows = sampleLines(SAMPLE, LANG, first).length;

const cardWidth = Math.max(
  Math.ceil(sampleColumns(SAMPLE, LANG, first) * CHAR),
  swatchWidth(TOKENS.length + 2, SWATCH, SWATCH_GAP),
);
const codeHeight = rows * LINE;
const cardHeight = PAD + TITLE + codeHeight + 14 + SWATCH + PAD;
const cardOuter = cardWidth + 2 * PAD;

const drawCard = ({ theme, export: name }: Entry, x: number, y: number): string => `
  <g transform="translate(${x} ${y})" font-family="${attr(FONT)}" font-size="${SIZE}">
    <rect width="${cardOuter}" height="${cardHeight}" rx="8" fill="${attr(theme.bg)}"/>
    <rect width="${cardOuter}" height="${cardHeight}" rx="8" fill="none"
      stroke="${attr(theme.fg)}" stroke-opacity=".18"/>
    <text x="${PAD}" y="${PAD + 11}" font-size="12.5" font-weight="600"
      fill="${attr(theme.fg)}">${escape(theme.name)}</text>
    <text x="${cardOuter - PAD}" y="${PAD + 11}" font-size="11" text-anchor="end"
      fill="${attr(theme.fg)}" fill-opacity=".55">${escape(name)}</text>
    <g>
      ${drawCode(sampleLines(SAMPLE, LANG, theme), PAD, PAD + TITLE)}
    </g>
    <g>
      ${drawSwatches(swatchSlots(theme), theme, PAD, PAD + TITLE + codeHeight + 14, SWATCH, SWATCH_GAP)}
    </g>
  </g>`;

const render = (cols: number): string => {
  const grid = Math.ceil(themes.length / cols);
  const width = cols * cardOuter + (cols - 1) * GAP + 2 * GAP;
  const legendTop = GAP + grid * (cardHeight + GAP);
  const height = legendTop + 34;

  const cards = themes.map((entry, i) =>
    drawCard(
      entry,
      GAP + (i % cols) * (cardOuter + GAP),
      GAP + Math.floor(i / cols) * (cardHeight + GAP),
    ),
  );

  const legend = ["fg", "numbers", ...TOKENS].join(" · ");

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"
  viewBox="0 0 ${width} ${height}" font-family="${attr(FONT)}">
  <title>rangi — bundled theme palettes</title>${cards.join("")}
  <text x="${GAP}" y="${legendTop + 12}" font-size="11" fill="${MUTED}">Swatches, left to right: ${escape(legend)}</text>
  <text x="${GAP}" y="${legendTop + 28}" font-size="11" fill="${MUTED}">A dashed swatch is a token the theme leaves undefined: it inherits fg. Generated by scripts/theme-palette.ts.</text>
</svg>
`;
};

const { values } = parseArgs({
  options: { out: { type: "string" }, columns: { type: "string" } },
});

const cols = Math.max(1, Number(values.columns ?? 3));
await writeSvg(values.out ?? "docs/themes.svg", render(cols), `${cols} columns`);
